image:
  # keep this in sync with the ExternalDNS helm chart version if needed
  tag: v0.19.0

logLevel: debug

namespaced: false

sources:
  - ingress
  - service

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/ionos-cloud/external-dns-ionos-webhook
      tag: v0.11.0
      pullPolicy: IfNotPresent
    env:
      - name: LOG_LEVEL
        value: debug
      - name: IONOS_API_KEY
        valueFrom:
          secretKeyRef:
            name: ionos-credentials
            key: api-key
